### ISSUE TITLE
Not sure how to obtain the auth token?

### ISSUE THREAD

**Issue by justinpeterson13** [drudge/homebridge-mobilelink#1]
I realize this is still in beta but am I able to give it a try? If so I'm not sure how to get the auth token or setup the config file.

**Comment by drudge** [comment]
Hi @justinpeterson13!

You're correct that the plugin is in beta right now! It doesn't have a ton of functionality at the moment. It creates a new `Outlet` on your Homebridge. The Outlet will set `In Use` based on when the generator is detected to be running.

My goal was to get basic automation in place with the Home+ app that automatically turns certain accessories off when running on generator power. I'm happy to report that the plugin does indeed achieve my goal.

If you're still feeling adventurous and want to try it out, you can generate a new auth token using `curl`. Edit the `UserLogin` and `UserPassword` values in the JSON request below to match your MobileLink account, and then copy and paste the command into your terminal and execute it.

```bash
curl -s -X "POST" "https://api.mobilelinkgen.com/Users/login" \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json' \
     -H 'User-Agent: StandbyStatusProd/1.4.9.3148 (iPhone; iOS 14.0; Scale/3.00)' \
     -d $'{
  "SharedKey": "GeneseeDepot13",
  "UserLogin": "your@email.com",
  "UserPassword": "password"
}' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'AuthToken'\042/){print $(i+1)}}}' | tr -d '"' | sed -n 1p
```
 As long as your credentials are correct, you'll see your new auth token printed to your terminal.

If you have [`homebridge-config-ui-x`](https://github.com/oznu/homebridge-config-ui-x#readme), you can enter your newly generated auth token in the settings screen to get started.

If you prefer to hand-edit your config.json, add a new object, similar to the one below, to your `platforms` array, replacing the value for `authToken` with your generated token: 

```json
{
    "authToken": "token",
    "discoverFrequency": 60000,
    "platform": "MobileLink"
}
```

If you don't mind me asking, is there something specific you're looking to achieve with the plugin?

**Comment by mdisabato** [comment]
Hi!

Thank you for your work on this project. Fascinating stuff!

I am new to HomeKit, but not new to tech. We are in the midst of an extensive home renovation, and plan to automate the house as much as possible to support *ahem* "aging in place". I saw this project on HomeBridge and added it (and HomeBridge) to my collection of experimental learnings. It appears to be working, and the Home and Home+ apps let me turn the status on and off, but I know it's not starting up the Generac. We have a test set for Saturday's, and I'll let you know what happens then. 

As for future usage, like you, I plan to shut down devices when the generator starts. Mostly that will be outside lighting, but we have two HVAC systems, and I plan to use this to shut one of them down through the Ecobee 4 thermostat linked to HomeKit. 

I'm adventurous (to a point :) ) and willing to try things if you do more development on this. 

Thanks again!

Stay safe out there.

Michael

**Comment by jgardner04** [comment]
@drudge Thanks for putting this together. I too can get the auth token and see my generator in homebridge. I have a whole home system with an auto transfer switch. I have the generator in standby, but the switch appears on. Is this expected?

**Comment by justinpeterson13** [comment]
Thanks!

I just got my Generac connected to wifi so I’m trying it out now. What is the “SharedKey” field?

Id like to have the plugin send a notification when the generator is running or stopped.

**Comment by justinpeterson13** [comment]
Got it working! Thanks again!

**Comment by drudge** [comment]
@justinpeterson13 Awesome, glad you got it working! It's pretty basic right now, but I've only reverse engineered some basics from the mobile app.

@mdisabato & @jgardner04 The device will always appear "On" as long as a connection to the generator can be made. I have not found a way to enable the generator remotely through the API. If you are aware of anything that does this, please share and I'll try to figure out how it works. 

As I mentioned in my first reply to @justinpeterson13, this integration will set the outlet to `In Use` when the generator is running. I use this with Home+ to configure an automation that does exactly as you describe. When the generator is running, the outlet changes to In Use, certain devices in the house are powered off to conserve energy. Additionally, I've added some monitoring to the battery voltage so you will get a low battery notification in the event that the battery doesn't maintain regular voltage.

 I'm always open to feedback and ways to improve the plugin so please share your feedback after you've tried it out.

**Comment by thcooley** [comment]
Is this Plugin Still alive? :-) I am attempting to get it working and I cannot figure out the Auth Key generation, attempted running the AuthKey curl as outlined in both my computer terminal and home bridge terminal and it returns no data, my next steps were going to be to dig into the command, etc.. to try to figure it out, but I am not super good at json etc.. so may take me awhile. Hoping someone on here may have a quick answer if this AuthKey curl command is still good and it could just be user error.

**Comment by coryabooth** [comment]
No...  Generac changed their API so this will need to change
