### ISSUE TITLE
API Solution?

### ISSUE THREAD

**Issue by coryabooth** [drudge/homebridge-mobilelink#14]
Seems openHAB found a recent work-around...

Curious if this may help?
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.generacmobilelink

    private synchronized void login() throws InterruptedException {
        GeneracMobileLinkAccountConfiguration config = getConfigAs(GeneracMobileLinkAccountConfiguration.class);
        refreshIntervalSeconds = config.refreshInterval;
        HTTPResult result = sendRequest(BASE_URL + "/Users/login", HttpMethod.POST, null,
                new StringContentProvider(
                        gson.toJson(new LoginRequestDTO(SHARED_KEY, config.username, config.password))),
                "application/json");
        if (result.responseCode == HttpStatus.OK_200) {
            LoginResponseDTO loginResponse = gson.fromJson(result.content, LoginResponseDTO.class);
            if (loginResponse != null) {
                authToken = loginResponse.authToken;
                updateStatus(ThingStatus.ONLINE);
            }
        } else {
            handleErrorResponse(result);
            if (thing.getStatusInfo().getStatusDetail() == ThingStatusDetail.CONFIGURATION_ERROR) {
                // bad credentials, stop trying to login
                stopPoll();
            }
        }
    }

    private void getStatuses(boolean retry) throws InterruptedException {
        if (authToken == null) {
            return;
        }
        HTTPResult result = sendRequest(BASE_URL + "/Generator/GeneratorStatus", HttpMethod.GET, authToken, null, null);
        if (result.responseCode == HttpStatus.OK_200) {
            generators = gson.fromJson(result.content, GeneratorStatusResponseDTO.class);
            updateGeneratorThings();
            if (getThing().getStatus() != ThingStatus.ONLINE) {
                updateStatus(ThingStatus.ONLINE);
            }
        } else {
            if (retry) {
                logger.debug("Retrying status request");
                getStatuses(false);
            } else {
                handleErrorResponse(result);
            }
        }
    }

**Comment by talldrin** [comment]
Any update on this?

**Comment by drudge** [comment]
I've published a beta package for v2 that supports the new MobileLinke API.
