### ISSUE TITLE
How to know if generator is running

### ISSUE THREAD

**Issue by bosephus190** [drudge/homebridge-mobilelink#17]
So I understand the switch being off represents the generator being offline, on represents the generator being online, and in use is the generator running. But, HomeKit won’t set an automation based on the in use state… only off and on.  Is there a way to set an automation for in use or set a second switch for when it’s in use?

**Comment by coryabooth** [comment]
Would it be possible to say:

If "inuse" = "on" else "off"

I would say we assume the generator is "online" as that would show in other ways.

**Comment by drudge** [comment]
I'm okay with that change if you'd like to submit a PR.

**Comment by coryabooth** [comment]
So if I understand this correctly, to make this compatible with HomeBridge statuses...  We could do this:

`      try {
        this.service.getCharacteristic(this.Characteristic.Name).updateValue(this.apparatus.name);
        /**this.service.getCharacteristic(this.Characteristic.On).updateValue(this.isReady());**/
        this.service.getCharacteristic(this.Characteristic.OutletInUse).updateValue(this.isReady());`

**Comment by jcapayne** [comment]
PR submitted as I was just looking for the same thing! https://github.com/drudge/homebridge-mobilelink/pull/19

**Comment by coryabooth** [comment]
> PR submitted as I was just looking for the same thing! #19

Thanks!

**Comment by drudge** [comment]
Version 2.1 has been released and works with the latest Mobile Link. The switch will be On when the generator is running and Off when it is not.
