### ISSUE TITLE
Support Off State from Generator

### ISSUE THREAD

**Issue by rfroom** [drudge/homebridge-mobilelink#2]
**Is your feature request related to a problem? Please describe:**
Love to see feature support for generator turning off and trigger the state to off

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by drudge** [comment]
Hi @rfroom, please see this entry in the FAQ. If I am able to find an API or method to controlling the run status, I'd love to implement it.

https://github.com/drudge/homebridge-mobilelink/wiki/FAQ#why-cant-i-power-onoff-the-generator-with-the-outlet
