### ISSUE TITLE
Auth token

### ISSUE THREAD

**Issue by steveintro** [drudge/homebridge-mobilelink#4]
How do I generate and/or find an auth token for mobile link?

thank you!

**Comment by drudge** [comment]
Hey @steveintro! Check out the FAQ for instructions on creating an auth token:

https://github.com/drudge/homebridge-mobilelink/wiki/FAQ#how-do-i-generate-an-auth-token

**Comment by bosephus19** [comment]
I tried using the terminal in the homebridge web interface and I copy/paste the code (update with user/pass) and I get no result.. do I need a mobilelink subscription to get an auth token?
