### ISSUE TITLE
Auth Token Broken?

### ISSUE THREAD

**Issue by bosephus19** [drudge/homebridge-mobilelink#7]
I've tried unsuccessfully to generate an auth token (no result generated in terminal) and I think it's because Generac changed the login URL, any suggestions?

I tried going to https://api.mobilelinkgen.com/Users/login and that didn't get me to a login screen 

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by drudge** [comment]
Generac has removed the old API and the new one is quite a bit different. I'm working on reverse engineering the new API and will update the plugin once I fully understand the changes.

**Comment by bosephus19** [comment]
Great, thanks!

**Comment by jcleek** [comment]
Any update on the rewrite?

**Comment by NickRivait** [comment]
Any update on this?

**Comment by mikesalz** [comment]
Hi @drudge It looks like there haven't been any updates to this plugin since 2020.  Just curious if fixing the API issue is something that is still on your radar?  Thanks!

**Comment by drudge** [comment]
> Hi @drudge It looks like there haven't been any updates to this plugin since 2020.  Just curious if fixing the API issue is something that is still on your radar?  Thanks!

Hi @mikesalz. Yes, I would love to work on this project some more but haven't had much luck reversing the new MobileLink platform. 

I'm still trying though as time permits. Any assistance would be fantastic.

**Comment by mikesalz** [comment]
> Any assistance would be fantastic.

Oh man, I would LOVE to help but I can barely spell python. :)
I am happy to assist with testing if you need some help there!

**Comment by NickRivait** [comment]
I also would love to help, but have no skills. 

Thank you,

Nick Rivait
226-881-0698
***@***.***

**Comment by brettferrell** [comment]
Commenting so I get updated if this is ever fixed...

**Comment by mdisabato** [comment]
I have networking skills, if that would help. I have a WiFi version of the controller that I plan to swap out for the Ethernet version this summer.

**Comment by jredondox** [comment]
@drudge any luck with this plug in?

**Comment by drudge** [comment]
I've published a beta package for v2 that supports the new MobileLinke API.

**Comment by mikesalz** [comment]
Thanks @drudge!  Just curious - Is this using a local API or cloud?

**Comment by drudge** [comment]
> Thanks @drudge! Just curious - Is this using a local API or cloud?

Hi @mikesalz, this is using their MobileLink cloud API similar to the previous version.

**Comment by coryabooth** [comment]
@drudge 

Got it working - shows as an "outlet" - but without the Generator running is shows "On" 
Will the outlet show "Off" when under Generator power?

**Comment by drudge** [comment]
> @drudge
> 
> Got it working - shows as an "outlet" - but without the Generator running is shows "On" Will the outlet show "Off" when under Generator power?

Similar to the initial release, the accessory will show as `On` as long as it is connected. The outlet will show `In Use` when it is running or exercising.

**Comment by coryabooth** [comment]
Thanks so much!  I never saw the initial version working so was unfamiliar. 

This is extremely important to me.  My generator is a 22k but I have a dual A/C setup. 

The single A/C can actually do just fine - so that was my decision to get the 22k

What I did not fully process is if I leave both A/C "on" and I loose power while away, I could kill the generator. 

This will allow me to tell one Ecobee to shut off when the genny is running.

**Comment by drudge** [comment]
Version 2.1 has been released and works with the latest Mobile Link. The switch will be On when the generator is running and Off when it is not.
